### ISSUE TITLE
font awesome 图标不显示

### ISSUE THREAD

**Issue by Tangtangchannel** [theme-particlex/hexo-theme-particlex#102]
如图：
![image](https://github.com/theme-particlex/hexo-theme-particlex/assets/92237766/5a6e4397-2115-4075-ae66-d302dd0a54ac)

咱不是很了解内部原理（
一个临时解决方法是插入fontawesome给的js

**Comment by Tangtangchannel** [comment]
![image](https://github.com/theme-particlex/hexo-theme-particlex/assets/92237766/6f3bb141-9a27-4e0d-b4ba-189fa93bbc69)
把这行无效的代码删掉（大概是这行
再添加你自己在fontawesome的script
<link rel="stylesheet" href="https://cdn.staticfile.org/font-awesome/6.4.2/css/all.min.css">

**Comment by real-jack** [comment]
我其实只有在safari浏览器上没有显示图标，切换到谷歌上就可以了，倒是代码自动换行的问题，我把highlight给关了，改成false，他就可以自动换行了

**Comment by Tangtangchannel** [comment]
> 我其实只有在safari浏览器上没有显示图标，切换到谷歌上就可以了，倒是代码自动换行的问题，我把highlight给关了，改成false，他就可以自动换行了

我这里反而是Google Chrome没有

**Comment by real-jack** [comment]
老哥，想问一下你把链接换成什么了啊，我在fontawesome上注册了一个账号，但没找到哪里有可以替换的链接。然后在网上用别人的链接，发现问题更多了，最后还是换回了原来的。想问一下，应该怎么改成自己的啊，谢谢

**Comment by Tangtangchannel** [comment]
> 老哥，想问一下你把链接换成什么了啊，我在fontawesome上注册了一个账号，但没找到哪里有可以替换的链接。然后在网上用别人的链接，发现问题更多了，最后还是换回了原来的。想问一下，应该怎么改成自己的啊，谢谢

去注册一个font awesome 就会给你一个script代码块

**Comment by LynxCatTheThird** [comment]
问题似乎出在 StaticFile 上，建议换成 BootCDN 应急
```html
<link href="https://cdn.bootcdn.net/ajax/libs/font-awesome/6.4.2/css/all.min.css" rel="stylesheet">
```

**Comment by argvchs** [comment]
https://github.com/staticfile/static/issues/662
