### ISSUE TITLE
关于博客一直卡在loading界面的问题

### ISSUE THREAD

**Issue by Michael-Zyx** [theme-particlex/hexo-theme-particlex#103]
本来是没有任何问题的，但当我自己尝试添加黑暗模式后，本地测试时博客就卡在了loading界面，按F12发现浏览器没有任何报错，但就是无法进入，相关的代码文件已经邮箱（3276959650@qq.com）发您了，希望您能协助看看，谢谢！

**Comment by Michael-Zyx** [comment]
@argvchs

**Comment by argvchs** [comment]
@YuziO2

**Comment by YuziO2** [comment]
已回复其邮件，摘要如下：
> 你可以点进去堆栈信息查看是哪一行报错了。
![image](https://github.com/theme-particlex/hexo-theme-particlex/assets/50757904/fc8926fb-9091-44e3-a4f0-272fb08f4fce)
> 这个DOM你没有设置，拿到的是null，当然没有removeAttribute方法了，于是报错。
这个DOM是用来设置代码块的黑暗模式的，你可以看看我的文章：
https://blog.yuzi.dev/posts/f53f778b.html#HighLightJS

**Comment by Michael-Zyx** [comment]
问题已解决，感谢两位大佬的协助！

解决摘要：
1、修改import.ejs中的路径使.min.css成功加载
2、main.js中缺少如下代码导致的卡在loading界面 [代码链接](https://github.com/theme-particlex/hexo-theme-particlex/blob/master/source/js/main.js#L13-L17)
![缺失代码](https://github.com/theme-particlex/hexo-theme-particlex/assets/116944782/812cfc08-44e8-4a93-bdfd-3bc7276fa8c3)

再次感谢！
