### ISSUE TITLE
improve: 替换字体与 Polyfill CDN

### ISSUE THREAD

**Issue by zonefile** [theme-particlex/hexo-theme-particlex#107]
Google Fonts 在国内有节点，比 fonts.loli.net 用的 Cloudflare 反而会快不少；Polyfill 在国内一些省份被墙，可以换成阿里的。

Replace `fonts.loli.net` to `fonts.googleapis.cn`, `gstatic.loli.net` to `fonts.gstatic.cn`, and `polyfill.io` to `polyfill.alicdn.com`

**Comment by famousprince** [comment]
https://sansec.io/research/polyfill-supply-chain-attack

Polyfill.io 供应链攻击已影响大量网站，是否有必要对仍在使用 v2.8.0 以前版本的用户进行提醒？
