### ISSUE TITLE
关于页面以及目录等界面是没有制作吗？

### ISSUE THREAD

**Issue by AuroBreeze** [theme-particlex/hexo-theme-particlex#115]
我点击之后没有看到其他的页面，这样我是不是要自己去写这样的页面去适配

**Comment by YashajinAlice** [comment]
> 我点击之后没有看到其他的页面，这样我是不是要自己去写这样的页面去适配
应该是要自己来才行，打着玩意会自动创建，后面就自行发挥了

hexo new page about
hexo new page categories
hexo new page tags
