### ISSUE TITLE
禁用Hexo自带高亮后,代码块未换行

### ISSUE THREAD

**Issue by Cokyswen** [theme-particlex/hexo-theme-particlex#82]
我尝试修改了main.css中第781行pre的样式,由white-space: normal改为white-space: pre之后代码块将能正常显示换行了.

**Comment by Cokyswen** [comment]
但是这样的话,整体布局将又不协调了....
![Screenshot_20230726_214007](https://github.com/theme-particlex/hexo-theme-particlex/assets/140519232/3890d104-f82f-4076-b57f-258086618c30)
![Screenshot_20230726_215253](https://github.com/theme-particlex/hexo-theme-particlex/assets/140519232/3c99a051-fdbc-41df-8205-e400ffdcc4c6)

**Comment by argvchs** [comment]
27e1e29

改完了，`innerText` 获取不到换行，换成 `textContent` 就可以了
