### ISSUE TITLE
跳转出现问题

### ISSUE THREAD

**Issue by bobsers** [theme-particlex/hexo-theme-particlex#84]
![image](https://github.com/theme-particlex/hexo-theme-particlex/assets/122640845/8e5b2584-2897-4f48-abf4-d3c61994517b)
点进去按理来说应该跳转到这里的
![image](https://github.com/theme-particlex/hexo-theme-particlex/assets/122640845/28f511ff-4d12-4d31-90ed-f23b1e7ade6e)
但是实际上是跳转到了这里
![image](https://github.com/theme-particlex/hexo-theme-particlex/assets/122640845/f1af7ded-742c-40d8-8180-fb3642916c6e)
文档页和分类页也有这个问题😭

**Comment by argvchs** [comment]
？？你是不是改了 `_config.yml`，`relative_link` 的值应该为 `false` 不然会变成相对路径

```yaml
relative_link: false
```

**Comment by bobsers** [comment]
哦哦是这样的，谢谢大佬
