### ISSUE TITLE
公式无法正常显示

### ISSUE THREAD

**Issue by Slongod** [theme-particlex/hexo-theme-particlex#90]
疑似会将 _ 识别为 markdown 的斜体，大公式 $$ $$ 也无法显示。
求大佬解答。
<img width="584" alt="image" src="https://github.com/theme-particlex/hexo-theme-particlex/assets/128909450/2948b012-4706-40a5-916b-8c4dcf6e9e09">
<img width="643" alt="image" src="https://github.com/theme-particlex/hexo-theme-particlex/assets/128909450/6c52e550-2eac-4a2f-8abd-7b20eb38a2d7">

**Comment by argvchs** [comment]
@Slongod 如果用 marked 渲染器必须要转义符号才能渲染 latex，如果不想用转义符号可以用 Pandoc

https://argvchs.github.io/2022/06/17/hexo-latex/

**Comment by Slongod** [comment]
@argvchs /bx
