### ISSUE TITLE
网站路径问题

### ISSUE THREAD

**Issue by 135shanchun** [theme-particlex/hexo-theme-particlex#93]
![屏幕截图 2023-10-04 155343](https://github.com/theme-particlex/hexo-theme-particlex/assets/111720307/5dc172bc-6231-490c-a09e-37412213dcbd)
请问这是怎么回事？为啥不能访问/tags和/categories但是可以访问其根目录
是我的config出现了问题嘛？
麻烦作者大大

**Comment by 135shanchun** [comment]
config里面是这样的，没看出有啥问题😭：
menu:
    Home:
        name: house
        theme: solid
        link: /
    About:
        name: id-card
        theme: solid
        link: /about
    Archives:
        name: box-archive
        theme: solid
        link: /archives
    Categories:
        name: bookmark
        theme: solid
        link: /categories
    Tags:
        name: tags
        theme: solid
        link: /tags

**Comment by argvchs** [comment]
@135shanchun 啊啊为什么总是有人不看[教程](https://argvchs.github.io/2022/04/17/hexo-blog-1)就来问（

```bash
hexo new page categories
hexo new page tags
```

然后照着我的更改一下：https://github.com/argvchs/blog/tree/master/source

**Comment by 135shanchun** [comment]
啊啊不好意思



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年10月04日 20:59 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [theme-particlex/hexo-theme-particlex] 网站路径问题 (Issue #93) |

@135shanchun 啊啊为什么总是有人不看教程就来问（

hexo new page categories
hexo new page tags

然后照着我的更改一下：https://github.com/argvchs/blog/tree/master/source
